### ISSUE TITLE
Request Queue does not remove requests once they have played

### ISSUE THREAD

**Issue by Poporacer** [FalconChristmas/fpp-plugin-ViewerControl#10] opened 2019-01-25 00:53 UTC

**Comment by KensingtonGraves** [comment] 2019-01-26 01:51
Also, the queue on the viewer site does not remove requests when they have been deleted from the queue using the FPP UI.

**Comment by cpinkham** [comment] 2019-01-28 04:04
> Also, the queue on the viewer site does not remove requests when they have been deleted from the queue using the FPP UI. That is, the songs disappear from the Viewer site queue, but the site reports that the queue is still full.

You have to reload the page.  I'm still working on making some of those things refresh on demand.

I think this original issue was due to permissions on the plugin's tmp directory.  I have pushed a fix for this so this can be fixed by an uninstall/reinstall of the plugin.

**Comment by cpinkham** [comment] 2019-01-28 04:16
Closing this since it is now reported working as intended.

**Closed by cpinkham** 2019-01-28 04:16 UTC
